name: Validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake g++ libreadline-dev libyaml-cpp-dev \
            dpkg-dev binutils libx11-dev libxpm-dev \
            libxft-dev libxext-dev python3 libssl-dev

      - name: Setup ROOT CERN
        uses: root-project/setup-root@v1
        with:
          version: '6.30.04'

      - name: Build and install
        run: |
          # Usamos una ruta con permisos de escritura
          export INSTALL_PATH=${{ github.workspace }}/install
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
          cmake --build build
          cmake --install build
          
          # Verificación final
          source $INSTALL_PATH/thisFEMDAQ.sh
          # FEMDAQRoot -b -q # Descomenta cuando confirmes que el binario existe
