name: Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
env:
  INSTALL_PATH: /femdaq/install
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libreadline-dev \
            libyaml-cpp-dev \
            dpkg-dev \
            binutils \
            libx11-dev \
            libxpm-dev \
            libxft-dev \
            libxext-dev \
            python3 \
            libssl-dev \
            libpcre3-dev \
            xlibmesa-glu-dev \
            libglew-dev \
            libftgl-dev \
            libfftw3-dev \
            libcfitsio-dev \
            libgraphviz-dev \
            libavahi-client-dev \
            libldap2-dev \
            libxml2-dev \
            libkrb5-dev \
            libgsl-dev \
            libqt5webengine5

      - name: Install ROOT CERN
        run:
          sudo apt-get install -y root-system-bin libroot-core-dev libroot-tree-dev

      - name: Build and install
        run: |
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PATH }}
          cmake --build build
          cmake --install build
          source ${{ env.INSTALL_PATH }}/thisFEMDAQ.sh
          FEMDAQRoot -b -q
          cmake ..
          make -j2

      - name: Run Tests
